version: "3.8"

services:
  # FastAPI backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # React frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  # PostgreSQL for application data (expensedb)
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: expenseuser
      POSTGRES_PASSWORD: expensepass
      POSTGRES_DB: expensedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis – required by Redash
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # Redash server (with worker included)
  redash:
    image: redash/redash:latest
    platform: linux/amd64
    container_name: redash
    ports:
      - "5050:5000"           # Redash UI
    environment:
      # Connection string for Redash's metadata database. It is recommended to use
      # a separate DB (e.g. redash) in the same Postgres server.
      REDASH_DATABASE_URL: "postgresql://expenseuser:expensepass@db:5432/redash"
      # Location of Redis for job queues
      REDASH_REDIS_URL: "redis://redis:6379/0"
      # Secret key for session cookies and other cryptographic features
      REDASH_COOKIE_SECRET: "a-super-secret-string"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
