services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: expenseuser
      POSTGRES_PASSWORD: expensepass
      POSTGRES_DB: expensedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  postgres_data:
